TIMER EQU 10H
PIC EQU 20H
EOI EQU 20H
N_CLK EQU 10
N_F10 EQU 9

ORG 36
IP_F10 DW RUT_F10
ORG 40
IP_CLK DW RUT_CLK

ORG 1000H
MSJ1 DB "Ingrese un numero: "
FINAL DB ?

ORG 1500H
NUM DB ?
DB 0AH

ORG 3000H
RUT_F10: PUSH AX
MOV AL, 0FDH ; 1111 1101
OUT PIC+1, AL ; PIC: registro IMR
MOV AL, EOI
OUT PIC, AL ; PIC: registro EOI
POP AX
IRET

RUT_CLK: PUSH AX
MOV AL, 2
INT 7
DEC NUM
DEC DL
JNZ FINRUT_CLK
INT 0
FINRUT_CLK: MOV AL, 0
OUT TIMER, AL ; TIMER: registro CONT
MOV AL, EOI
OUT PIC, AL ; PIC: registro EOI
POP AX
IRET

ORG 2000H
MOV BX, OFFSET MSJ1
MOV AL, OFFSET FINAL - OFFSET MSJ1
INT 7
MOV BX, OFFSET NUM
INT 6
MOV DL, NUM
SUB DL, 30H
CLI
MOV AL, 0FEH  ; 1111 1110
OUT PIC+1, AL ; PIC: registro IMR
MOV AL, N_F10
OUT PIC+4, AL ; PIC: registro INT0
MOV AL, N_CLK
OUT PIC+5, AL ; PIC: registro INT1
MOV AL, 1
OUT TIMER+1, AL ; TIMER: registro COMP
MOV AL, 0
OUT TIMER, AL ; TIMER: registro CONT
STI
LAZO: JMP LAZO
INT 0
END