TIMER EQU 10H
PIC EQU 20H
EOI EQU 20H
N_CLK EQU 10
N_F10 EQU 9

ORG 36
IP_F10 DW RUT_F10
ORG 40
IP_CLK DW RUT_CLK

ORG 1000H


ORG 3000H
RUT_F10: PUSH AX
IN AL, PIC+1
CMP AL, 0FEH
JNZ SIG_F10
MOV AL, 0FCH ; 1111 1100
OUT PIC+1, AL ; PIC: registro IMR
JMP FINRUT_F10
SIG_F10: MOV AL, 0FEH
OUT PIC+1, AL ; PIC: registro IMR
FINRUT_F10: POP AX
MOV AL, EOI
OUT PIC, AL ; PIC: registro EOI
IRET

RUT_CLK: PUSH AX
INC DL
CMP DL, 30
JNZ FINRUT_CLK
INT 0
FINRUT_CLK: MOV AL, 0
OUT TIMER, AL ; TIMER: registro CONT
MOV AL, EOI
OUT PIC, AL ; PIC: registro EOI
POP AX
IRET

ORG 2000H
MOV DL, 0
CLI
MOV AL, 0FEH  ; 1111 1110
OUT PIC+1, AL ; PIC: registro IMR
MOV AL, N_F10
OUT PIC+4, AL ; PIC: registro INT0
MOV AL, N_CLK
OUT PIC+5, AL ; PIC: registro INT1
MOV AL, 1
OUT TIMER+1, AL ; TIMER: registro COMP
MOV AL, 0
OUT TIMER, AL ; TIMER: registro CONT
STI
LAZO: JMP LAZO
END
